apps/system/urls.py
# -*- coding: UTF-8 -*-
# __author__ : RobbieHan
# __data__  : 2017/12/8

from django.conf.urls import url

from system import views

urlpatterns = [
    # 系统工具
    url(r'^system_setup/$', views.SystemSetupView.as_view(), name="system_setup"),
    url(r'^email_setup/$', views.EmailSetupView.as_view(), name="email_setup"),
]

apps/users/urls.py
# -*- coding: UTF-8 -*-
# __author__ : RobbieHan
# __data__  : 2017/12/8

from django.conf.urls import url

from users import views_user, views_structure

urlpatterns = [
    # 用户增改删查操作
    url(r'^user/$', views_user.UserView.as_view(), name="user"),
    url(r'^user/list$', views_user.UserListView.as_view(), name="user-list"),
    url(r'^user/detail$', views_user.UserDetailView.as_view(), name="user-detail"),
    url(r'^user/update$', views_user.UserUpdataView.as_view(), name="user-update"),
    url(r'^user/create$', views_user.UserCreateView.as_view(), name="user-create"),
    url(r'^user/delete$', views_user.UserDeleteView.as_view(), name="user-delete"),
    url(r'^user/enable$', views_user.UserEnableView.as_view(), name="user-enable"),
    url(r'^user/disable$', views_user.UserDisableView.as_view(), name="user-disable"),
    url(r'^user/adminpasswdchange$', views_user.AdminPasswdChangeView.as_view(), name="user-adminpasswdchange"),

    # 组织架构的改删查操作
    url(r'^structure/$', views_structure.StructureView.as_view(), name="structure"),
    url(r'^structure/list$', views_structure.StructureListView.as_view(), name="structure-list"),
    url(r'^structure/detail$', views_structure.StructureDetailView.as_view(), name="structure-detail"),
    url(r'^structure/delete$', views_structure.StructureDeleteView.as_view(), name="structure-delete"),
    url(r'^structure/add_user$', views_structure.Structure2UserView.as_view(), name="structure-add_user"),
]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

gistandard/urls.py
# -*- coding: utf-8 -*-
"""gistandard URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.views.static import serve
from gistandard.settings import MEDIA_ROOT

import xadmin

from users.views_user import LoginView, IndexView, LogoutView
from system.views import SystemView
from adm.views import AdmView
from personal import views as personal_views
from personal import views_work_order as order

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^$', IndexView.as_view(), name='index'),
    # 用户登录
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),

    url(r'^system/$', SystemView.as_view(), name="system"),
    url(r'^system/basic/', include('users.urls', namespace='system-basic')),
    url(r'^system/rbac/', include('rbac.urls', namespace='system-rbac')),
    url(r'^system/tools/', include('system.urls', namespace='system-tools')),

    url(r'^adm/$', AdmView.as_view(), name="adm-main"),
    url(r'^adm/bsm/', include('adm.urls', namespace='adm-bsm')),
    url(r'^adm/equipment/', include('adm.urls_equipment', namespace='adm-equipment')),
    url(r'^adm/asset/', include('adm.urls_asset', namespace='adm-asset')),
    url(r'^adm/company/', include('adm.urls_company', namespace='adm-company')),

    url(r'^personal/$', personal_views.PersonalView.as_view(), name="personal"),
    url(r'^personal/userinfo', personal_views.UserInfoView.as_view(), name="personal-user_info"),
    url(r'^personal/uploadimage', personal_views.UploadImageView.as_view(), name="personal-uploadimage"),
    url(r'^personal/passwordchange', personal_views.PasswdChangeView.as_view(), name="personal-passwordchange"),
    url(r'^personal/phonebook', personal_views.PhoneBookView.as_view(), name="personal-phonebook"),
    url(r'^personal/workorder_Icrt/$', order.WorkOrderView.as_view(), name="personal-workorder_Icrt"),
    url(r'^personal/workorder_Icrt/list', order.WorkOrderListView.as_view(), name="personal-workorder-list"),
    url(r'^personal/workorder_Icrt/create', order.WorkOrderCreateView.as_view(), name="personal-workorder-create"),
    url(r'^personal/workorder_Icrt/detail', order.WorkOrderDetailView.as_view(), name="personal-workorder-detail"),
    url(r'^personal/workorder_Icrt/delete', order.WorkOrderDeleteView.as_view(), name="personal-workorder-delete"),
    url(r'^personal/workorder_Icrt/update', order.WorkOrderUpdateView.as_view(), name="personal-workorder-update"),
    url(r'^personal/workorder_app/$', order.WorkOrderView.as_view(), name="personal-workorder_app"),
    url(r'^personal/workorder_app/send', order.WrokOrderSendView.as_view(), name="personal-workorder-send"),
    url(r'^personal/workorder_rec/$', order.WorkOrderView.as_view(), name="personal-workorder_rec"),
    url(r'^personal/workorder_rec/execute', order.WorkOrderExecuteView.as_view(), name="personal-workorder-execute"),
    url(r'^personal/workorder_rec/finish', order.WorkOrderFinishView.as_view(), name="personal-workorder-finish"),
    url(r'^personal/workorder_rec/upload', order.WorkOrderUploadView.as_view(), name="personal-workorder-upload"),
    url(r'^personal/workorder_rec/return', order.WorkOrderReturnView.as_view(), name="personal-workorder-return"),
    url(r'^personal/workorder_Icrt/upload', order.WorkOrderProjectUploadView.as_view(),
        name="personal-workorder-project-upload"),
    url(r'^personal/workorder_all/$', order.WorkOrderView.as_view(), name="personal-workorder_all"),
    url(r'^personal/document/$', order.WorkOrderDocumentView.as_view(), name="personal-document"),
    url(r'^personal/document/list', order.WorkOrderDocumentListView.as_view(), name="personal-document-list"),

]

apps/system/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.


class SystemSetup(models.Model):
    loginTitle = models.CharField(max_length=20, null=True, blank=True, verbose_name='登录标题')
    mainTitle = models.CharField(max_length=20, null=True, blank=True, verbose_name='系统标题')
    headTitle = models.CharField(max_length=20, null=True, blank=True, verbose_name='浏览器标题')
    copyright = models.CharField(max_length=100, null=True, blank=True, verbose_name='底部版权信息')
    url = models.CharField(max_length=50, null=True, blank=True, verbose_name='系统URL地址')


    def __str__(self):
        return self.loginTitle

    class Meta:
        verbose_name = "系统设置"
        verbose_name_plural = verbose_name

    @classmethod
    def getSystemSetupLastData(self):
        return dict(system_setup=SystemSetup.objects.last())


class EmailSetup(models.Model):
    emailHost = models.CharField(max_length=30, verbose_name='SMTP服务器')
    emailPort = models.IntegerField(verbose_name='SMTP端口')
    emailUser = models.EmailField(max_length=100, verbose_name='邮箱帐号')
    emailPassword = models.CharField(max_length=30, verbose_name='邮箱密码')

    def __str__(self):
        return self.emailHost

    class Meta:
        verbose_name = '发件邮箱设置'
        verbose_name_plural = verbose_name

    @classmethod
    def getEmailSetupLastData(self):
        return EmailSetup.objects.last()

apps/users/models.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser

from rbac.models import Role


class UserProfile(AbstractUser):
    """
    用户: makemigration提示错误：sers.UserProfile.user_permissions: (fields.E304)，
    需要在settings中指定自定义认证模型：AUTH_USER_MODEL = 'users.UserProfile'
    """
    name = models.CharField(max_length=20, default="", verbose_name="姓名")
    birthday = models.DateField(null=True, blank=True, verbose_name="出生日期")
    gender = models.CharField(max_length=10, choices=(("male", "男"), ("famale", "女")), default="male",
                              verbose_name="性别")
    mobile = models.CharField(max_length=11, default="", verbose_name="电话")
    email = models.EmailField(max_length=100, verbose_name="邮箱")
    image = models.ImageField(upload_to="image/%Y/%m", default="image/default.jpg", max_length=100, null=True,
                              blank=True)
    department = models.ForeignKey("Structure", null=True, blank=True, verbose_name="部门")
    post = models.CharField(max_length=50, null=True, blank=True, verbose_name="职位")
    superior = models.ForeignKey("self", null=True, blank=True, verbose_name="上级主管")
    roles = models.ManyToManyField("rbac.Role", verbose_name="角色", blank=True)
    joined_date = models.DateField(null=True, blank=True, verbose_name="入职日期")

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name


class Structure(models.Model):
    """
    组织架构
    """
    type_choices = (("firm", "公司"), ("department", "部门"))
    title = models.CharField(max_length=60, verbose_name="名称")
    type = models.CharField(max_length=20, choices=type_choices, default="department", verbose_name="类型")
    parent = models.ForeignKey("self", null=True, blank=True, verbose_name="父类架构")

    class Meta:
        verbose_name = "组织架构"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

apps/system/forms.py
# -*- coding: UTF-8 -*-
# __author__ : RobbieHan
# __data__  : 2017/10/12

import re

from django import forms
from .models import SystemSetup


class SystemSetupForm(forms.ModelForm):
    class Meta:
        model = SystemSetup
        fields = '__all__'

apps/system/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import render
from django.views.generic.base import View
from django.http import HttpResponse
from django.conf import settings

from utils.mixin_utils import LoginRequiredMixin
from rbac.models import Menu
from .models import SystemSetup
from .forms import SystemSetupForm

# Create your views here.

class SystemView(LoginRequiredMixin, View):
    """
    系统模块入口
    """
    def get(self, request):
        return render(request, 'system/system_index.html')


class SystemSetupView(LoginRequiredMixin, View):
    """
    系统基本配置：create
    """

    def get(self, request):
        ret = Menu.getMenuByRequestUrl(url=request.path_info)
        ret.update(SystemSetup.getSystemSetupLastData())
        return render(request, 'system/tools/system-setup.html', ret)

    def post(self, request):
        res = dict(result=False)
        system_setup_form = SystemSetupForm(request.POST)
        if system_setup_form.is_valid():
            system_setup_form.save()
            res['result'] = True
        return HttpResponse(json.dumps(res), content_type='application/json')


class EmailSetupView(LoginRequiredMixin, View):
    """
    发件邮箱设置：create
    """

    def get(self, request):
        ret = Menu.getMenuByRequestUrl(url=request.path_info)
        ret.update(SystemSetup.getSystemSetupLastData())
        return render(request, 'system/tools/email-setup.html', ret)

templates/system/structure/structure-list.html
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}">
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
{% endblock %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header margin-bottom">
  <ol class="breadcrumb">
    <li><a href=""><i class="fa fa-dashboard"></i>办公平台</a></li>
    <li class="active"><a href="{{ menu.parent.parent.url }}">{{ menu.parent.parent.title }}</a></li>
    <li class="active"><a href="{{ menu.url }}">{{ menu.title }}</a></li>
  </ol>
</section>
    <!-- Main content -->
  <section class="content">
     <div id="devlist">
        <div class="box box-primary" id="liebiao">
            <div class="box-header">
                <div class="btn-group pull-left">
                    <button type="button" id="btnRefresh" class="btn btn-default">
                        <i class="glyphicon glyphicon-repeat"></i>刷新
                    </button>
                </div>
                <div class="btn-group pull-left">&nbsp</div>
                <div class="btn-group pull-left">
                    <button type="button" id="btnCreate" class="btn btn-default">
                        <i class="glyphicon glyphicon-plus"></i>新增
                    </button>

                </div>
                <div class="btn-group pull-left">&nbsp</div>
                <div class="btn-group pull-left">
                    <button type="button" id="btnDelete" class="btn btn-default">
                        <i class="glyphicon glyphicon-trash"></i>删除
                    </button>
                </div>
            </div>
            <div class="box-body">
                <table id="dtbList" class="display" cellspacing="0" width="100%">
                    <thead>
                    <tr valign="middle">
                        <th><input type="checkbox" id="checkAll"></th>
                        <th>ID</th>
                        <th>名称</th>
                        <th>类别</th>
                        <th>所属</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <br> <br>
            </div>
        </div>
     </div>
  </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'plugins/datatables/dataTables.const.js' %}"></script>
  <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
  <!-- iCheck 1.0.1 -->
  <script type="text/javascript">
	$(function() {
	    $('#SYSTEM-BASIC').addClass('active');
		$('#SYSTEM-BASIC-STRUCTURE').addClass('active');

	});
  </script>

    <script type="text/javascript">
var oDataTable=null;
$(function() {
	oDataTable = initTable();
	function initTable() {
		var oTable=$('#dtbList').DataTable($.extend(true,{},
						DATATABLES_CONSTANT.DATA_TABLES.DEFAULT_OPTION,
						{
							ajax : {
								"url":"{% url 'system-basic:structure-list' %}",
								"data":function ( d ) {
									d.select=$("#select").val();
								}
						},
						columns : [
								DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,
								{
									data : "id",
									width : "5%",
								},
								{
									data : "title",//parent
									width : "20%",
								},

								{
									data : "type",
                                    render : function(data, type, row, meta) {
										if (data=='firm'){
											return "公司";
										}else if(data=='department'){
											return "部门";
										}
									}
								},
                                {
									data : "parent__title",
								},

								{
									data : "id",
									width : "12%",
									bSortable : "false",
									render : function(data, type, row, meta) {
										var ret="";
										var ret="<button title='详情-编辑' onclick='doUpdate("
										+ data + ")'><i class='glyphicon glyphicon-pencil'></i></button>";
										ret=ret+"<button title='关联用户' onclick='doAddUser("
                                            + data + ")'><i class='glyphicon glyphicon-user'></i></button>";
										 ret=ret+"<button title='删除' onclick='doDelete("
                                            + data + ")'><i class='glyphicon glyphicon-trash'></i></button>";
										return ret;
									}
								} ],
						"order":[
                    [1, 'id']
		 	           ],
						}));
		return oTable;
	}

	//checkbox全选
    $("#checkAll").on("click", function () {
        if ($(this).prop("checked") === true) {
            $("input[name='checkList']").prop("checked", $(this).prop("checked"));
            $('#example tbody tr').addClass('selected');
        } else {
            $("input[name='checkList']").prop("checked", false);
            $('#example tbody tr').removeClass('selected');
        }
    });


	$("#btnCreate").click(function() {
		layer.open({
			type : 2,
			title : '新增',
			shadeClose : false,
			maxmin : true,
			area : [ '800px', '400px' ],
			content : "{% url 'system-basic:structure-detail' %}",
			end : function() {
				//关闭时做的事情
				oDataTable.ajax.reload();
			}
		});
	});

	$("#btnRefresh").click(function(){
		oDataTable.ajax.reload();
	});

	//批量删除
	$("#btnDelete").click(function() {
		if ($("input[name='checkList']:checked").length == 0){
			layer.msg("请选择要删除的记录");
			return ;
		}

		var arrId= new Array();
		$("input[name='checkList']:checked").each(function(){
			//alert($(this).val());
			arrId.push($(this).val());
		});

		sId=arrId.join(',');

		layer.alert('用户组下的用户也将会被删除，确定删除吗？', {
			title:'提示'
			,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
			,time: 0 //不自动关闭
			,btn: ['YES', 'NO']
			,yes: function(index){
			 	layer.close(index);
			 	$.ajax({
					type: "POST",
					url : "{% url 'system-basic:structure-delete' %}",
					data : {"id":sId, csrfmiddlewaretoken: '{{ csrf_token }}'},
					cache: false,
					success : function(msg) {
						if (msg.result){
							layer.alert("操作成功",{icon:1});
							oDataTable.ajax.reload();
						}else{
							//alert(msg.message);
							layer.alert("操作失败",{icon:2});
						}
						return ;
					}
				});
			}
		});
	});


});

function doUpdate(id){
	layer.open({
		type : 2,
		title : '编辑',
		shadeClose : false,
    	maxmin : true,
		area : [ '800px', '400px' ],
		content : [ "{% url 'system-basic:structure-detail' %}"+'?id='+id, 'no' ],
		end : function() {
			oDataTable.ajax.reload();
		}
	});
}


//删除单个数据
function doDelete(id){
    layer.alert('当前组内用户也会被删除，确定删除吗？', {
        title:'提示'
        ,icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
        ,time: 0 //不自动关闭
        ,btn: ['YES', 'NO']
        ,yes: function(index){
            layer.close(index);
            $.ajax({
                type: "POST",
                url : "{% url 'system-basic:structure-delete' %}",
                data : {"id":id, csrfmiddlewaretoken: '{{ csrf_token }}'},  //防止post数据时报 csrf_token 403
                cache: false,
                success : function(msg) {
                    if (msg.result){
                        layer.alert('删除成功',{icon: 1});
                        oDataTable.ajax.reload();
                    }else{
                        //alert(msg.message);
                        layer.alert('删除失败', {icon: 2});
                    }
                    return ;
                }
            });
        }
    });

}

//关联用户
function doAddUser(id){
	layer.open({
		type : 2,
		title : '编辑',
		shadeClose : false,
		maxmin : true,
		area : [ '800px', '600px' ],
		content : [ "{% url 'system-basic:structure-add_user' %}"+'?id='+id, 'no' ],
		end : function() {
			window.location.reload();
		}
	});
}

</script>
{% endblock %}

templates/system/structure/structure_detail.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
{% endblock %}

{% block main %}
<div class="box box-danger">
	<form class="form-horizontal" id="addForm" method="post">
		{% csrf_token %}
		<input type="hidden" name='id' value="{{ structure.id }}" />
		<div class="box-body">
          <fieldset>
            <legend>
              <h4>组织架构信息</h4>
            </legend>
            <div class="form-group has-feedback">
                <label class="col-sm-2 control-label">名称</label>
                <div class="col-sm-3">
                    <input class="form-control" name="title" type="text" value="{{ structure.title }}"/>
                </div>
                <label class="col-sm-2 control-label">类别</label>
                <div class="col-sm-3">
                  <select class="form-control" name="type">
                    <option value={{ structure.type }}> {{ structure.get_type_display|default:"--类别--" }} </option>
                    <option value="firm">公司</option>
                    <option value="department">部门</option>
                  </select>
                </div>

            </div>

            <div class="form-group has-feedback">
                <label class="col-sm-2 control-label">所属</label>
                <div class="col-sm-3">
                  <select class="form-control" name="parent">
                    <option value={{ structure.parent_id|default_if_none:"" }}> {{ structure.parent.title|default:"" }} </option>
                    <option></option>
                    {% for s in structures %}
                    <option value={{ s.id }}> {{ s.title}} </option>
                    {% endfor %}
                  </select>
                </div>
            </div>
          </fieldset>

		</div>
		<div class="box-footer ">
			<div class="row span7 text-center ">
              <button type="button" id="btnCancel" class="btn btn-default margin-right " >重置</button>
              <button type="button" id="btnSave" class="btn btn-info margin-right " >保存</button>
			</div>
		</div>

	</form>
</div>

{% endblock %}

{% block javascripts %}
<script src="{% static 'plugins/combo-select/jquery.combo.select.js' %}"></script>
<script type="text/javascript">

	$("#btnSave").click(function(){
		var data = $("#addForm").serialize();
		$.ajax({
			type: $("#addForm").attr('method'),
			url : "{% url 'system-basic:structure-detail' %}",
			data : data,
			cache: false,
			success : function(msg) {
				if (msg.result){
					layer.alert('数据保存成功！', {icon: 1},function(index){
					    parent.layer.closeAll(); //关闭所有弹窗
                    });
				}else{
					layer.alert('数据保存失败', {icon: 5});
                    //$('errorMessage').html(msg.message)
				}
				return ;
			}
		});
	});


	/*点取消刷新新页面*/
    $("#btnCancel").click(function () {
	    window.location.reload();

    });

</script>

{% endblock %}

templates/system/structure/structure_user.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
{% endblock %}
{% block main %} 
<div class="box box-danger">
	<form class="form-horizontal" id="selectUsersForm" action="" method="post">
		{% csrf_token %} 
		<input type="hidden" name='id' value="{{ structure.id }}" />
		<div class="box-body">
			<div class="row">
				<div class="col-xs-5">
					<label class="control-label">可选用户:</label>
					<select name="from" id="multiselect" class="form-control" size="18" multiple="multiple">
						{% for item in un_add_users %}
							<option value="{{ item.id }}" >{{ item.name }}({{ item.username }})</option>
						{% endfor %}
					</select>
				</div>
				<div class="col-xs-2">
					<br><br><br><br><br><br>
					<button type="button" id="multiselect_rightAll" class="btn btn-block"><i class="glyphicon glyphicon-forward"></i></button>
					<button type="button" id="multiselect_rightSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
					<button type="button" id="multiselect_leftSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
					<button type="button" id="multiselect_leftAll" class="btn btn-block"><i class="glyphicon glyphicon-backward"></i></button>
				</div>
				<div class="col-xs-5">
					<label class="control-label">已绑定用户:</label>
					<select name="to" id="multiselect_to" class="form-control" size="18" multiple="multiple">
						{% for item in added_users %}
							<option value="{{ item.id }}" >{{ item.name }}({{ item.username }})</option>
						{% endfor %}
					</select>
				</div>
			</div>
            <div class="row">
                <div class="col-xs-12 margin-top-5">
                    <p class="text-maroon">*注意：一个用户只能隶属一个部门，如果选择的用户已存在部门，用户将会从原有部门移出</p>
                </div>
			</div>
		</div>
		<div class="box-footer ">
			<div class="row span7 text-center ">
              <button type="button" id="btnCancel" class="btn btn-default margin-right " >重置</button>
              <button type="button" id="btnSave" class="btn btn-info margin-right " >保存</button>
			</div>
		</div>
	</form>
</div>
{% endblock %}

{% block javascripts %}
<script src="{% static 'plugins/select/multiselect.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
	//初始化多选列表
	 $('#multiselect').multiselect({
        search: {
            left: '<input type="text" class="form-control" placeholder="Search..." />',
            right: '<input type="text" class="form-control" placeholder="Search..." />',
        },
        fireSearch: function(value) {
            return value.length > 3;
        }
    });


});

$("#btnSave").click(function(){
		$('#multiselect_to option').prop('selected', true);
		var data =$("#selectUsersForm").serialize();
		console.log(data);
		$.ajax({
			type: $("#selectUsersForm").attr('method'),
			url : "{% url 'system-basic:structure-add_user' %}",
			data : data,
			cache: false,
			success : function(msg) {
				if (msg.result){
					layer.alert('操作成功',{icon:1});
				}else{
					//alert(msg.message);
					layer.alert('操作失败',{icon:2});
				}
				return ;
			}
		});
});

	/*点取消刷新新页面*/
    $("#btnCancel").click(function () {
	    window.location.reload();

    });
</script>
{% endblock %}